# Usage:
# docker-compose build
# docker-compose up
# docker-compose up -d
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
    ports:
      - '8001:80'
    volumes:
      - .:/home/app
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=web
      - MYSQL_DB=web
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local

